### PR TITLE
Unify OpenBSD ztypes; adds arm support

### PR DESCRIPTION
**Pull request by phy1729**
OpenBSD supports go on aarch64, amd64, arm, arm64, armv7, and i386[0]. 

`struct ptmget` and `PTMGET` are defined as [1]
```
struct ptmget {
	int	cfd;
	int	sfd;
	char	cn[16];
	char	sn[16];
};
#define PTMGET _IOR('t', 1, struct ptmget) /* get ptys */
```

`_IOR` is defined as [2]
```
#define	IOC_OUT		(unsigned long)0x40000000
[...]
#define	_IOC(inout,group,num,len) \
	(inout | ((len & IOCPARM_MASK) << 16) | ((group) << 8) | (num))
[...]
#define	_IOR(g,n,t)	_IOC(IOC_OUT,	(g), (n), sizeof(t))
```

The only thing that can vary between architectures is the size of int and on all OpenBSD go arches int is 32 bits.

The GOARCH build constraint is to prevent possibly introducing a tricky to diagnose bug and prod someone to think about if the new arch has 32 bit ints.

0: https://github.com/openbsd/ports/blob/02149e13191e61fde4fa7de89ace05492ca15b6d/infrastructure/mk/arch-defines.mk#L27
1: https://github.com/openbsd/src/blob/3ddf179c951256438053c2d92edb80da28a6c1cd/sys/sys/tty.h#L67-L73
2: https://github.com/openbsd/src/blob/3ddf179c951256438053c2d92edb80da28a6c1cd/sys/sys/ioccom.h#L52-L63

### CODE REVIEW

**Comment by creack** [comment]
cc @kr, should we reconsider the ztype file generation? IIRC freebsd had a similar case. I am wondering if it wouldn't be easier to just manage types manually instead of adding exceptions.

**Comment by creack** [comment]
@phy1729 thank you for the PR and for the detailed links to openbsd to back up the change. I'll try to test it asap with a vm..

**Comment by kr** [comment]
> cc @kr, should we reconsider the ztype file generation? IIRC freebsd had a similar case. I am wondering if it wouldn't be easier to just manage types manually instead of adding exceptions.

Good question. I don’t have much intuition for which way would be easier in the long run. But I do think that’s the right question to ask.

**Comment by creack** [comment]
LGTM, tested without issue.

**Pull request merged**
