### PR TITLE
Add loongarch support

### PR DESCRIPTION
**Pull request by chenguoqi-cc**
Signed-off-by: guoqi.chen <chenguoqi@loongson.cn>

### CODE REVIEW

**Comment by chenguoqi-cc** [comment]
Loongarch is loognson's newly released RISC architectureshat supports 32 and 64-bit modes and looks more like risc-v

**Comment by creack** [comment]
I am going to merge as it doesn't break anything and is gated by build tags, however, when you can, please reply here with the requested info as we need to test it.

**Comment by chenguoqi-cc** [comment]
I'm sorry that I didn't reply to your message in time, because longarch is a new architecture. The golang compiler has been transplanted, and the internal quality test is still in progress, so it hasn't been released yet. It is expected to be released by the end of July 2021, and we also plan to share it with golang's community.

For this patch, I have verified it on our loongarch machine. I'll let you know as soon as the code of our golang compiler is published。

**Comment by xen0n** [comment]
This patch might need revisiting -- actually even the canonical GOARCH value hasn't been decided yet! See golang/go#46229 for that matter.

@chenguoqi-cc: thanks for pushing upstream work for LoongArch (even if you are working on it full-time); but next time please wait before submitting changes that depend on not-yet-upstream things, to reduce churn and maintenance burden.

**Pull request merged**
