### PR TITLE
Add riscv64 support

### PR DESCRIPTION
**Pull request by carlosedp**
Add riscv64 support

### CODE REVIEW

**Comment by carlosedp** [comment]
Any news on this?

**Comment by creack** [comment]
Sorry for the delay. I just have no way to test it. I'll trust that you did and it works on riskv64 :).

When I find some time, I'll test the branch to make sure compilation on all other platforms also still works.

**Comment by carlosedp** [comment]
No probs, here is the output of the test app. I've added a `replace` directive to use my branch instead of the original module:

```
carlosedp in ~/work/test-pty at fedora-unleashed via 🐹 devel:f980a63fcb
➜ cat main.go
package main

import (
	"github.com/kr/pty"
	"io"
	"os"
	"os/exec"
)

func main() {
	c := exec.Command("grep", "--color=auto", "bar")
	f, err := pty.Start(c)
	if err != nil {
		panic(err)
	}

	go func() {
		f.Write([]byte("foo\n"))
		f.Write([]byte("bar\n"))
		f.Write([]byte("baz\n"))
		f.Write([]byte{4}) // EOT
	}()
	io.Copy(os.Stdout, f)
}

carlosedp in ~/work/test-pty at fedora-unleashed via 🐹 devel:f980a63fcb
➜ cat go.mod
module test-pty

replace github.com/kr/pty => github.com/carlosedp/pty v1.1.5-0.20190529160142-f0d8df56dd44

go 1.12

require github.com/kr/pty v1.1.5

carlosedp in ~/work/test-pty at fedora-unleashed via 🐹 devel:f980a63fcb
➜ cat go.sum
github.com/carlosedp/pty v1.1.5-0.20190529160142-f0d8df56dd44 h1:9X3bgVuSDSruOy/CALG43GCLD8qrP0l8/ZwDXTOb6GA=
github.com/carlosedp/pty v1.1.5-0.20190529160142-f0d8df56dd44/go.mod h1:9r2w37qlBe7rQ6e1fg1S/9xpWHSnaqNdHD3WcMdbPDA=

carlosedp in ~/work/test-pty at fedora-unleashed via 🐹 devel:f980a63fcb
➜ go build .

carlosedp in ~/work/test-pty at fedora-unleashed via 🐹 devel:f980a63fcb
➜ ./test-pty
foo
bar
baz
bar
```

Thanks!

**Comment by creack** [comment]
Would you be able to quickly tell me how to test this?

I got a go compiler working on `riscv` which works when adding the build tag to your PR. I haven't managed to find a riscv64 go compiler. I always get `compile: unknown architecture "riscv64"`

**Comment by creack** [comment]
I'll merge for now as it doesn't break the other builds and allows compilation on that arch, but please let me know if there is a way I could test it.

**Comment by carlosedp** [comment]
Go is still not upstreamed. You need to build https://github.com/4a6f656c/riscv-go. 

I added instructions how to build in the tracker: https://github.com/carlosedp/riscv-bringup

**Comment by creack** [comment]
Thanks, i'll take a look.

**Pull request merged**
