### PR TITLE
add z/OS support

### PR DESCRIPTION
**Pull request by MacMalainey**
adds z/OS target support

### CODE REVIEW

**Comment by creack** [comment]
Would it be possible to follow the pattern used in pty_darwin.go, pty_freebsd.go & co, i.e. implement ptsname, unlockpt, etc instead of adding the sys/unix dependency?

**Comment by MacMalainey** [comment]
> Would it be possible to follow the pattern used in pty_darwin.go, pty_freebsd.go & co, i.e. implement ptsname, unlockpt, etc instead of adding the sys/unix dependency?

Done - note that it does depend on some runtime functions that are only present in the IBM maintained z/OS port of the Go compiler/library (just in case you were wondering where those functions came from)

**Comment by creack** [comment]
thanks! looks good. Does the runtime thing mean we require cgo on zos?

**Comment by MacMalainey** [comment]
No, CGO won't be required!

**Review by creack — APPROVED** [review]

**Comment by creack** [comment]
tagged and released. Thanks!

**Pull request merged**
